# <font color = orange > Analise Explaroratoria da empresa e motivos de saidas dos funcionarios.

- Esse arquivo está sendo criado para mostrar o relatorio de saidas dos funcionarios da empresa e nele sera usado o Pandas que é uma biblioteca de software escrita para a linguagem de programação Python que fornece recursos de manipulação e análise de dados.NumPy, que significa Numerical Python, é um pacote fundamental para computação científica em Python.Matplotlib é uma biblioteca multiplataforma e multifuncional capaz de produzir gráficos estáticos, animados e interativos em vários estilos, formatos e mídias


- Importando as blibliotecas que serao usadas para analise de demisao desse projeto.

In [3]:
import pandas as pd
import numpy as np


- Criando grafico com os dados fornecidos pela empresa assim tendo melhores insights e facilidade de visualizao com isso conseguimos dar melhores explicacoes sobre o projeto e motivos por suas demisoes.

In [4]:
Resultados_e_Descobertas = {'Causas de saida ' : ['Treinamento','Conflito com outros', 'Falta de reconhecimento', 'Carga horaria', 'Progressao de carreira', 'Remuneracao', 'Tipo de trabalho', 'Mudanca de carreira','Trajeto', 'Realocaçao','Doença'],
                      'Capacidade de impactar'  : [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1],
                      'Recursos humanos' : [31,11,65,14,137,16,128,18,31,105,9],
                      'Entrevistas de saida' :[23 ,15, 44, 39, 171, 24, 78, 30 ,22, 37, 21]}

relatorio = pd.DataFrame(Resultados_e_Descobertas, index= [0,1,2,3,4,5,6,7,8,9,10])
relatorio

Causas de saida   Capacidade de impactar  Recursos humanos  \
0               Treinamento                      11                31   
1       Conflito com outros                      10                11   
2   Falta de reconhecimento                       9                65   
3             Carga horaria                       8                14   
4    Progressao de carreira                       7               137   
5               Remuneracao                       6                16   
6          Tipo de trabalho                       5               128   
7       Mudanca de carreira                       4                18   
8                   Trajeto                       3                31   
9                Realocaçao                       2               105   
10                   Doença                       1                 9   

    Entrevistas de saida  
0                     23  
1                     15  
2                     44  
3                     39  
4                    171  
5                     24  
6                     78  
7                     30  
8                     22  
9                     37  
10                    21

- Parte feita pra obter resultados do grafico tendo os motivos de maiores saidas da empresa sendo na entrevista de saida e na parte de recursos humanos e o relatorio sobre a capacidade de impactar assim podemos ter melhor insights sabendo o que esta acontecendo na empresa.

In [5]:
relatorio['Entrevistas de saida'].max()

171

In [6]:
relatorio['Recursos humanos']. max()

137

In [7]:
relatorio['Capacidade de impactar']. max()

11

##O que está sendo mostrado aqui?

![image.png](https://github.com/Rodrigomarques02/Resultados_e_descobertas/blob/main/graficos_usados/2023-08-30%20(5).png?raw=true)

- Acima podemos ver um grafico de bolhas que mostra o relatorio de saidas dos funcionarios da empresa sua capacidade de impactar e seus motivos que sao Treinamento, Conflito com outros, Falta de reconhecimento, Carga horária, Progressão de carreira,Remuneração, Tipo de trabalho, Mudança de carreira, Trajeto ,Realocação, Doença.
Ao olhar pode se parecer dificil de entender o grafico de bolha por isso usaria o de barra pra facilitar na vizualizao e facilitar pras pessoas que nao tem o conhecimneto em leitura de graficos pois a atenção humana é um recurso limitado
e quanto mais facil a leitura do grafico mais facil fica a compreensao naquilo que esta sendo mostrado.


## Que observações você pode fazer a partir desses dados?





- Com os dados obtidos no grafico podemos analisar as causas de saida da empresa a Capacidade de impactar, as causas de saidas da empresa tem bastantes divergencias quando sao feitas pelo RH e quando elas fazem por si so, analisando o grafico podemos ve o quanto as pessoas querem crescer na empresa pois e esse motivo que mais causa a saida delas o progresso de carreira.

- Gráficos de barras usa o comprimento para representar as medidas. Seres
humanos são excelentes para identificar diferenças de comprimentos de uma
mesma base. Esse tipo de gráfico é muito efetivo para comparar categorias.

![image.png](https://github.com/Rodrigomarques02/Resultados_e_descobertas/blob/main/graficos_usados/2023-09-01.png?raw=true)

## O que não é ideal ou poderia ser evitado na visualização em sua forma atual? Que perguntas você faria ou que feedback daria para quem fez o gráfico?

- Eu acho que nesse grafico poderia ter mudado a cor que indica o que cada causa de saida indica pois por serem parecidas acaba confundindo vizualmente.
Quando foi criar o grafico por que nao optou por colocar um grafico de barras nao acharia melhor e mais facil a entender?


# Crie três maneiras diferentes de mostrar esses dados e liste quais são algumas vantagens e insuficiências de cada uma.

- Grafico de barras onde podemos analisar que temos as repostas dos Recursos humanos e das intrevistas de saidas e a capacidade de impactar nele podemos analisar com mais facilidade cada dado nele obtido com isso podemos obter insights mais certos e com isso obtendo melhores resultados e menas chances de erros.
Um ponto que devemos tomar cuidado e que como podemos ver quando se tem bastante informacoes no grafico de barras ele acaba escondendo algumas informacoes com isso atrapalha na visualizacao e na hora de explicar.

![image.png](https://github.com/Rodrigomarques02/Resultados_e_descobertas/blob/main/graficos_usados/2023-09-01.png?raw=true)

- Grafico de arvore
O gráfico de árvore,  conhecido como "treemap", e tambem conhecidos como árvores de decisão ou diagramas de árvore, têm várias vantagens quando se trata de representar dados ou informações complexas de forma hierárquica. Aqui estão algumas das principais vantagens dos gráficos de árvore Estrutura Hierárquica Clara os gráficos de árvore organizam dados ou informações em uma estrutura hierárquica, o que facilita a compreensão de relações complexas entre diferentes categorias ou elementos. Isso torna mais fácil para os usuários identificarem a relação de subordinação e agrupamento entre os elementos,Uma desvantagem significativa dos gráficos de árvore especialmente no contexto de visualização de dados, como árvores de treemap é a seguinte dificuldade em Comparar Proporções e Tamanhos.

![image.png](https://github.com/Rodrigomarques02/Resultados_e_descobertas/blob/main/graficos_usados/2023-09-01%20(2).png?raw=true)

- Grafico de barra empilhada.
Os gráficos de barras empilhadas podem ser uma ferramenta útil para representar dados em algumas situações, mas também têm algumas limitações um ponto positivo e a sua comparação de partes para o todo, mais tambem tem seu grande problema com sua dificuldade em comparar categorias esportivas.

![image.png](https://github.com/Rodrigomarques02/Resultados_e_descobertas/blob/main/graficos_usados/2023-09-01%20(3).png?raw=true)

# Qual visualização representa melhor os dados e por quê?

- O gráficos de barras pois usa o comprimento para representar as medidas,seres
humanos são excelentes para identificar diferenças de comprimentos de uma
mesma base, esse tipo de gráfico é muito efetivo para comparar categorias a atenção humana é um recurso limitado entao quanto mais facil a visualizacao dos dado podemos aumentar a eficiência do ser humano no processo de
análise de dados e tomada de decisão.

#  Como você pode gerar essas informações em uma história orientada por dados para seu chefe?

- Querendo mostrar a importancia de uma grafico com melhor vizualicao criei um grafico de barras com os dados obtidos pela empresa e nele eu pude obter resultados que ajudam a ter respostas bastantes significativas, podemos analizar que em progressao de carreira  tivemos 171 votos nas Entrevistas de saida  comparados com os 137 votos do Recursos humanos mostrando que se tivermos a mesma quantidade de entrevistados nos 2 podemos ver que tem divergencias é bom preucuramos o motivo de saber o real motivo se as pessoas realmente estao querendo crescer na empresa, por que elas nao estao crescendo e sim saindo, sera que nao tem cargos maiores ou sera que nao tem oportunidades pra que possam crescer e um ponto bastante importante a ser avaliado.
Outro ponto a ser bastante avaliado é a realocacao muitas das vezes uma pessoa pode ser realocada pra um lugar mais disntante da sua residencia e isso acaba desmotivando e ate mesmo fazendo com que a pessoa saia da empresa pois seu tempo de locomocao aumenta trazendo mais desgaste ao longo do tempo.